module.exports = {
	data:[
		{className:'row',color:'#fff',title:'UTC−12 Y (BIT)',tmz:-12, search:'BIT Baker Island Time'},
{className:'row',color:'#fff',title:'UTC−11:30 X (NUT)',tmz:-11.5, search:'NUT Niue Time'},
{className:'row',color:'#fff',title:'UTC−11 X (SST)',tmz:-11, search:'SST Samoa Standard Time'},
{className:'row',color:'#fff',title:'UTC−10 W (HST)',tmz:-10, search:'HST Hawaii Standard Time'},
{className:'row',color:'#fff',title:'UTC−09:30 V (MIT)',tmz:-9.5, search:'MIT Marquesas Islands Time'},
{className:'row',color:'#fff',title:'UTC−09 V (GIT)',tmz:-9, search:'GIT Gambier Island Time'},
{className:'row',color:'#fff',title:'UTC−08 U (PST)',tmz:-8, search:'PST Pacific Standard Time (North America)'},
{className:'row',color:'#fff',title:'UTC−07 T (MST)',tmz:-7, search:'MST Mountain Standard Time (North America)'},
{className:'row',color:'#fff',title:'UTC−06 S (CST)',tmz:-6, search:'CST Central Standard Time (North America)'},
{className:'row',color:'#fff',title:'UTC−05 R (EST)',tmz:-5, search:'EST Eastern Standard Time (North America)'},
{className:'row',color:'#fff',title:'UTC−04:30 Q (VET)',tmz:-4.5, search:'VET Venezuelan Standard Time'},
{className:'row',color:'#fff',title:'UTC−04 Q (AST)',tmz:-4, search:'AST Atlantic Standard Time'},
{className:'row',color:'#fff',title:'UTC−03:30 P (NST)',tmz:-3.5, search:'NST Newfoundland Standard Time'},
{className:'row',color:'#fff',title:'UTC−03 P (UYT)',tmz:-3, search:'UYT Uruguay Standard Time'},
{className:'row',color:'#fff',title:'UTC−02:30 O (NDT)',tmz:-2.5, search:'NDT Newfoundland Daylight Time'},
{className:'row',color:'#fff',title:'UTC-02 O (FNT)',tmz:-2, search:'FNT Fernando de Noronha Time'},
{className:'row',color:'#fff',title:'UTC−01 N (AZOST)',tmz:-1, search:'AZOST Azores Standard Time'},
{className:'row',color:'#fff',title:'UTC Z (GMT)',tmz:0, search:'GMT Greenwich Mean Time'},
{className:'row',color:'#fff',title:'UTC+01 A (CET)',tmz:1, search:'CET Central European Time'},
{className:'row',color:'#fff',title:'UTC+02 B (EET)',tmz:2, search:'EET Eastern European Time'},
{className:'row',color:'#fff',title:'UTC+03 C (AST)',tmz:3, search:'AST Arabic Standard Time (Baghdad)'},
{className:'row',color:'#fff',title:'UTC+03:30 C (IRST)',tmz:3.5, search:'IRST Iran Standard Time'},
{className:'row',color:'#fff',title:'UTC+04 D (GST)',tmz:4, search:'GST Gulf Standard Time'},
{className:'row',color:'#fff',title:'UTC+04:30 D (AFT)',tmz:4.5, search:'AFT Afghanistan Time'},
{className:'row',color:'#fff',title:'UTC+05 E (PKT)',tmz:5, search:'PKT Pakistan Standard Time'},
{className:'row',color:'#fff',title:'UTC+05:30 E (IST)',tmz:5.5, search:'IST Indian Standard Time'},
{className:'row',color:'#fff',title:'UTC+05:45 E (NPT)',tmz:5.75, search:'NPT Nepal Time'},
{className:'row',color:'#fff',title:'UTC+06 F (BST)',tmz:6, search:'BST Bangladesh Standard Time'},
{className:'row',color:'#fff',title:'UTC+06:30 F (MST)',tmz:6.5, search:'MST Myanmar Standard Time'},
{className:'row',color:'#fff',title:'UTC+07 G (THA)',tmz:7, search:'THA Thailand Standard Time'},
{className:'row',color:'#fff',title:'UTC+08 H (WST)',tmz:8, search:'WST Western Standard Time'},
{className:'row',color:'#fff',title:'UTC+08:45 H (CWST)',tmz:8.75, search:'CWST Central Western Standard Time (Australia)'},
{className:'row',color:'#fff',title:'UTC+09 I (JST)',tmz:9, search:'JST Japan Standard Time'},
{className:'row',color:'#fff',title:'UTC+09:30 I (ACST)',tmz:9.5, search:'ACST Australian Central Standard Time'},
{className:'row',color:'#fff',title:'UTC+10 K (AEST)',tmz:10, search:'AEST Australian Eastern Standard Time'},
{className:'row',color:'#fff',title:'UTC+10:30 K (LHST)',tmz:10.5, search:'LHST Lord Howe Standard Time'},
{className:'row',color:'#fff',title:'UTC+11 L (PONT)',tmz:11, search:'PONT Pohnpei Standard Time'},
{className:'row',color:'#fff',title:'UTC+11:30 L (NFT)',tmz:11.5, search:'NFT Norfolk Time'},
{className:'row',color:'#fff',title:'UTC+12 M (NZST)',tmz:12, search:'NZST New Zealand Standard Time'},
{className:'row',color:'#fff',title:'UTC+12:45 M (CHAST)',tmz:12.75, search:'CHAST Chatham Standard Time'},
{className:'row',color:'#fff',title:'UTC+13 M (TOT)',tmz:13, search:'TOT Tonga Time'},
{className:'row',color:'#fff',title:'UTC+13:45 M (CHADT)',tmz:13.75, search:'CHADT Chatham Daylight Time'},
{className:'row',color:'#fff',title:'UTC+14 M (TKT)',tmz:14, search:'TKT Tokelau Time'}
	]
}
