module.exports = {
	data:[
		{className:'row',color:'#fff',title:'GMT -12 (BIT) Y',tmz:-12, search:'BIT Baker Island Time', id:0},
{className:'row',color:'#fff',title:'GMT -11:30 (NUT) X',tmz:-11.5, search:'NUT Niue Time', id:1},
{className:'row',color:'#fff',title:'GMT -11 (SST) X',tmz:-11, search:'SST Samoa Standard Time', id:2},
{className:'row',color:'#fff',title:'GMT -10 (HST) W',tmz:-10, search:'HST Hawaii Standard Time', id:3},
{className:'row',color:'#fff',title:'GMT -09:30 (MIT) V',tmz:-9.5, search:'MIT Marquesas Islands Time', id:4},
{className:'row',color:'#fff',title:'GMT -09 (GIT) V',tmz:-9, search:'GIT Gambier Island Time', id:5},
{className:'row',color:'#fff',title:'GMT -08 (PST) U',tmz:-8, search:'PST Pacific Standard Time (North America)', id:6},
{className:'row',color:'#fff',title:'GMT -07 (MST) T',tmz:-7, search:'MST Mountain Standard Time (North America)', id:7},
{className:'row',color:'#fff',title:'GMT -06 (CST) S',tmz:-6, search:'CST Central Standard Time (North America)', id:8},
{className:'row',color:'#fff',title:'GMT -05 (EST) R',tmz:-5, search:'EST Eastern Standard Time (North America)', id:9},
{className:'row',color:'#fff',title:'GMT -04:30 (VET) Q',tmz:-4.5, search:'VET Venezuelan Standard Time', id:10},
{className:'row',color:'#fff',title:'GMT -04 (AST) Q',tmz:-4, search:'AST Atlantic Standard Time', id:11},
{className:'row',color:'#fff',title:'GMT -03:30 (NST) P',tmz:-3.5, search:'NST Newfoundland Standard Time', id:12},
{className:'row',color:'#fff',title:'GMT -03 (UYT) P',tmz:-3, search:'UYT Uruguay Standard Time', id:13},
{className:'row',color:'#fff',title:'GMT -02:30 (NDT) O',tmz:-2.5, search:'NDT Newfoundland Daylight Time', id:14},
{className:'row',color:'#fff',title:'GMT -02 (FNT) O',tmz:-2, search:'FNT Fernando de Noronha Time', id:15},
{className:'row',color:'#fff',title:'GMT -01 (AZOST) N',tmz:-1, search:'AZOST Azores Standard Time', id:16},
{className:'row',color:'#fff',title:'GMT  (GMT) Z',tmz:0, search:'GMT Greenwich Mean Time', id:17},
{className:'row',color:'#fff',title:'GMT +01 (CET) A',tmz:1, search:'CET Central European Time', id:18},
{className:'row',color:'#fff',title:'GMT +02 (EET) B',tmz:2, search:'EET Eastern European Time', id:19},
{className:'row',color:'#fff',title:'GMT +03 (AST) C',tmz:3, search:'AST Arabic Standard Time (Baghdad)', id:20},
{className:'row',color:'#fff',title:'GMT +03:30 (IRST) C',tmz:3.5, search:'IRST Iran Standard Time', id:21},
{className:'row',color:'#fff',title:'GMT +04 (GST) D',tmz:4, search:'GST Gulf Standard Time', id:22},
{className:'row',color:'#fff',title:'GMT +04:30 (AFT) D',tmz:4.5, search:'AFT Afghanistan Time', id:23},
{className:'row',color:'#fff',title:'GMT +05 (PKT) E',tmz:5, search:'PKT Pakistan Standard Time', id:24},
{className:'row',color:'#fff',title:'GMT +05:30 (IST) E',tmz:5.5, search:'IST Indian Standard Time', id:25},
{className:'row',color:'#fff',title:'GMT +05:45 (NPT) E',tmz:5.75, search:'NPT Nepal Time', id:26},
{className:'row',color:'#fff',title:'GMT +06 (BST) F',tmz:6, search:'BST Bangladesh Standard Time', id:27},
{className:'row',color:'#fff',title:'GMT +06:30 (MST) F',tmz:6.5, search:'MST Myanmar Standard Time', id:28},
{className:'row',color:'#fff',title:'GMT +07 (THA) G',tmz:7, search:'THA Thailand Standard Time', id:29},
{className:'row',color:'#fff',title:'GMT +08 (WST) H',tmz:8, search:'WST Western Standard Time', id:30},
{className:'row',color:'#fff',title:'GMT +08:45 (CWST) H',tmz:8.75, search:'CWST Central Western Standard Time (Australia)', id:31},
{className:'row',color:'#fff',title:'GMT +09 (JST) I',tmz:9, search:'JST Japan Standard Time', id:32},
{className:'row',color:'#fff',title:'GMT +09:30 (ACST) I',tmz:9.5, search:'ACST Australian Central Standard Time', id:33},
{className:'row',color:'#fff',title:'GMT +10 (AEST) K',tmz:10, search:'AEST Australian Eastern Standard Time', id:34},
{className:'row',color:'#fff',title:'GMT +10:30 (LHST) K',tmz:10.5, search:'LHST Lord Howe Standard Time', id:35},
{className:'row',color:'#fff',title:'GMT +11 (PONT) L',tmz:11, search:'PONT Pohnpei Standard Time', id:36},
{className:'row',color:'#fff',title:'GMT +11:30 (NFT) L',tmz:11.5, search:'NFT Norfolk Time', id:37},
{className:'row',color:'#fff',title:'GMT +12 (NZST) M',tmz:12, search:'NZST New Zealand Standard Time', id:38},
{className:'row',color:'#fff',title:'GMT +12:45 (CHAST) M',tmz:12.75, search:'CHAST Chatham Standard Time', id:39},
{className:'row',color:'#fff',title:'GMT +13 (TOT) M',tmz:13, search:'TOT Tonga Time', id:40},
{className:'row',color:'#fff',title:'GMT +13:45 (CHADT) M',tmz:13.75, search:'CHADT Chatham Daylight Time', id:41},
{className:'row',color:'#fff',title:'GMT +14 (TKT) M',tmz:14, search:'TKT Tokelau Time', id:42},
	]
}
